export const data = [
    {
        question: "What does CSS stand for?",
        option1: "Colorful Style Sheets",
        option2: "Cascading Style Sheets ",
        option3: "Creative Style Sheets",
        option4: "Computer Style Sheets",
        ans: 2,
    },
    {
        question: "Where in an HTML document is the correct place to refer to an external style sheet?",
        option1: "In the <head> section ",
        option2: "At the end of the document",
        option3: "In the <body> section",
        option4: "None Of The Above",
        ans: 1,
    },
    {
        question: "Which HTML tag is used to define an internal style sheet?",
        option1: "<style>",
        option2: "<script>",
        option3: "<css>",
        option4: "<internal>",
        ans: 1,
    },
    {
        question: "Which HTML attribute is used to define inline styles?",
        option1: "class",
        option2: "style",
        option3: "font",
        option4: "styles",
        ans: 2,
    },
    {
        question: "Which is the correct CSS syntax?",
        option1: "{body;color:black;}",
        option2: "body:color=black;",
        option3: "{body:color=black;}",
        option4: "body {color: black;} ",
        ans: 4,
    },
    {
        question: "Which is the correct CSS syntax?",
        option1: "// this is a comment ",
        option2: "' this is a comment",
        option3: "/* this is a comment */  ",
        option4: "// this is a comment // ",
        ans: 3,
    },
    {
        question: "Which property is used to change the background color?",
        option1: "bgcolor",
        option2: "background-color",
        option3: "color",
        option4: "None",
        ans: 2,
    },
    {
        question: "Which CSS property controls the text size?",
        option1: "font-style",
        option2: "text-size",
        option3: "font-size",
        option4: "text-style",
        ans: 3,
    },
    {
        question: "What is the correct CSS syntax for making all the <p> elements bold?",
        option1: "p {text-size:bold;} ",
        option2: "p {font-weight:bold;}",
        option3: "<p style='text-size:bold;'>",
        option4: "<p style='font-size:bold;'>",
        ans: 2,
    },
    {
        question: "How do you display hyperlinks without an underline?",
        option1: "a {text-decoration:none;}  ",
        option2: "a {decoration:no-underline;}",
        option3: "a {underline:none;}>",
        option4: "a {text-decoration:no-underline;}>",
        ans: 1,
    },
    {
        question: "How do you make each word in a text start with a capital letter?",
        option1: "You can't do that with CSS",
        option2: "text-style:capitalize",
        option3: "text-transform:capitalize",
        option4: "transform:capitalize",
        ans: 3,
    },
    {
        question: "How do you select an element with id 'demo'?",
        option1: "#demo",
        option2: ".demo",
        option3: "*demo",
        option4: "demo",
        ans: 1,
    },
    {
        question: "How do you select elements with class name 'test'?",
        option1: "*test",
        option2: ".test",
        option3: "test",
        option4: "#test",
        ans: 2,
    },
    {
        question: "What is the default value of the position property?",
        option1: "absolute",
        option2: "relative",
        option3: "fixed",
        option4: "static",
        ans: 4,
    },
    {
        question: "Which property is used to change the left margin of an element",
        option1: "margin-left ",
        option2: "padding-left",
        option3: "indent",
        option4: "text-left",
        ans: 1,
    },
]