export const data = [
    {
        question: "What does HTML stand for?",
        option1: "Hyper Text Markup Language",
        option2: "Home Tool Markup Language",
        option3: "Hyperlinks Text Markup Language",
        option4: "Hyper Text Machine Language",
        ans: 1,
    },
    {
        question: "Choose the correct HTML element for the largest heading?",
        option1: "<h6>",
        option2: "<head>",
        option3: "<heading>",
        option4: "<h1>",
        ans: 4,
    },
    {
        question: "What is the correct HTML element for inserting a line break?",
        option1: "<break>",
        option2: "<br>",
        option3: "<lb>",
        option4: "<nextline>",
        ans: 2,
    },
    {
        question: "Choose the correct HTML element to define important text?",
        option1: "<important>",
        option2: "<strong>",
        option3: "<b>",
        option4: "<i>",
        ans: 2,
    },
    {
        question: "How can you open a link in a new tab/browser window?",
        option1: "<a href='url' new>",
        option2: "<a href='url' target='_blank'>  ",
        option3: "<a href='url' target='self_blank'>",
        option4: "<a href='url' target='new'>",
        ans: 2,
    },
    {
        question: "Which of these elements are all <table> elements?",
        option1: "<table><tr><td>",
        option2: "<thead><body><tr>",
        option3: "<table><head><tfoot>",
        option4: "<table><tr><tt>",
        ans: 1,
    },
    {
        question: "Choose the correct HTML element to define emphasized text?",
        option1: "<i>",
        option2: "<italic>",
        option3: "<em>",
        option4: "<emphasize>",
        ans: 3,
    },
    {
        question: "What is the correct HTML for creating a hyperlink?",
        option1: "<a name='http://www.quiz.com'>quiz.com</a>",
        option2: "<a>http://www.quiz.com</a",
        option3: "<a url='http://www.quiz.com'>quiz.com</a>",
        option4: "<a href='https://www.quiz.com'>quiz</a>  ",
        ans: 4,
    },
    {
        question: "Which character is used to indicate an end tag?",
        option1: "^",
        option2: "*",
        option3: "/",
        option4: "<",
        ans: 3,
    },
    {
        question: "How can you make a numbered list?",
        option1: "<list>",
        option2: "<dl>",
        option3: "<ul>",
        option4: "<ol>",
        ans: 4,
    },
    {
        question: "How can you make a bulleted list?",
        option1: "<list>",
        option2: "<dl>",
        option3: "<ul>",
        option4: "<ol>",
        ans: 3,
    },
    {
        question: "What is the correct HTML for making a checkbox?",
        option1: "<input type='check'>",
        option2: "<input type='checkbox'>  ",
        option3: "<checkbox>",
        option4: "<check>",
        ans: 2,
    },
    {
        question: "What is the correct HTML for making a text input field?",
        option1: "<input type='text'> ",
        option2: "<textinput type='text'>",
        option3: "<textfield>",
        option4: "<input type='textfield'>",
        ans: 1,
    },
    {
        question: "What is the correct HTML for making a drop-down list?",
        option1: "<input type='list'>",
        option2: "<list>",
        option3: "<input type='dropdown'>",
        option4: "<select>",
        ans: 4,
    },
    {
        question: "What is the correct HTML for inserting an image?",
        option1: "<img href='image.gif' alt='MyImage'>",
        option2: "<img src='image.gif' alt='MyImage'> ",
        option3: "<img alt='MyImage'>image.gif</img>",
        option4: "<image src='image.gif' alt='MyImage'>",
        ans: 2,
    },
   
]